### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by dlinyj**
Hello!

I've added a Makefile to your project. Using build scripts is bad practice. Firstly, they need to be made executable, and secondly, it is difficult to track dependencies. I don't recommend doing that. Therefore, I made a classic practice with a makefile.

To compile and build a project, just type _make_ . In order to run it in the emulator qemu, you need to enter the command _make runqemu_.

Thanks for the cool project!

### CODE REVIEW

**Comment by maniekx86** [comment]
Yes, I know build scripts are generally bad - that was just my laziness as the project is not very big (you also can see some bad practices in code too, probably I gonna fix them soon). 
There are the only three small issues that I see:
https://github.com/maniekx86/stillalive-os/blob/47b8a7140c30ab228952e6a8531bec5d1962e1a5/Makefile#L17-L18
As mount can sometimes fail, `mkdir` can fail when already directory exists. I think adding `rm -rf fdd/` before should do the job. How I said mount can fail: I don't know is it system configuration/distro/version but in my case mount without `-t msdos -o loop` refuses to mount as, so it should stay in place I guess. And lastly for `make runqemu`: this project plays music on PC speaker so we just need `-soundhw pcspk` to hear audio.

Well, after that changes I can merge. I am only not sure with `mount` line, let me know if mount works for you without additional options and with them. I also plan to change in the future all this copying demo.bin lines with something that does not require root access (maybe mcopy from mtools?).

Anyway thanks for the contribution!

**Comment by dlinyj** [comment]
I have added the changes you requested.

Also added a gitignore file. In order to avoid an error when creating a folder, I added the -p option. Checked everything works correctly.

I don't like the decision to create a file system with mformat. Because I had to install additional packages. But I couldn’t do it quickly with the help of dd and mkfs.

In general, using sudo in Makefile is a bad practice. But I still don't know how to do it more gracefully.

**Comment by maniekx86** [comment]
Yep, everything works great now, Thanks.

I think mformat is the simplest way to create FAT12 image with bootloader (there is actually some other FAT12 stuff in the MBR than just bootloader). I think it should be possible to create a filesystem with dd and mkfs but that would require root. Yet, mformat and mentioned before mcopy that could be used instead mounting are part of mtools - GNU project note: _Mtools is a collection of utilities to access MS-DOS disks from GNU and Unix without mounting them_ so I think it's not that bad as the only additional package for this project (it is way better than sudo anyway). Actually I gonna probably try that.

**Comment by dlinyj** [comment]
_I think it should be possible to create a filesystem with dd and mkfs but that would require root._ 

If you're working with a regular regular file, you don't need to be root. I was also too lazy to do it well, so I left your method :).

I think this is a good option. I don't like just using sudo.

**Pull request merged**
